wepquiz/wepquiz/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizformative.urls')),
    # path('', include('django.contrib.auth.urls')),
]

wepquiz/quizformative/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from datetime import datetime, timedelta
import pytz



class Quiz(models.Model):
    maker = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    startDateTime = models.DateTimeField(null=True)
    timeLimit = models.IntegerField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("quiz-detail", kwargs={"pk": self.pk})
        # return reverse("quiz-detail", pk=self.pk)

    @property
    def endDateTime(self):
        return self.startDateTime + timedelta(minutes=self.timeLimit)

    def hasStarted(self):
        now = datetime.now().replace(tzinfo=pytz.UTC)
        return now > self.startDateTime

    def isOver(self):
        now = datetime.now().replace(tzinfo=pytz.UTC)
        return now >= self.endDateTime

    def getStartDate(self, dateFormat='%Y-%m-%d'):
        startDateTime = self.startDateTime

        if startDateTime is not None:
            startDate = startDateTime.date().strftime(dateFormat)
        else:
            startDate = None

        return startDate

    def getStartTime(self, timeFormat='%H:%M'):
        startDateTime = self.startDateTime

        if startDateTime is not None:
            startTime = startDateTime.time().strftime(timeFormat)
        else:
            startTime = None

        return startTime

    @property
    def totalPoints(self):
        return sum(question.point for question in self.question_set.all())



class QuestionManager(models.Manager):
    def mcq_questions(self):
        return self.get_queryset().filter(type='mcq')

    def checkbox_questions(self):
        return self.get_queryset().filter(type='checkbox')

    def short_questions(self):
        return self.get_queryset().filter(type='short')


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.CharField(max_length=500)
    point = models.IntegerField()
    type = models.CharField(max_length=20, null=True)

    objects = QuestionManager()

    def __str__(self):
        return str(self.question)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=500)

    def __str__(self):
        return str(self.choice)


class McqAnswer(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    answer = models.IntegerField()

    def __str__(self):
        return str(self.answer)


class CheckboxAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.IntegerField()

    def __str__(self):
        return str(self.answer)


class ShortAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()

    def __str__(self):
        return str(self.answer)

wepquiz/templates/quiz/3dot_menu.html
<!-- from https://codepen.io/ryanmorr/pen/vLKvqe -->
<div class="more">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-three-dots-vertical"
        viewBox="0 0 16 16">
        <path
            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
    </svg>
    <div class="more-menu">
        <div class="more-menu-caret">
            <div class="more-menu-caret-outer"></div>
            <div class="more-menu-caret-inner"></div>
        </div>
        <ul class="more-menu-items" tabindex="-1" role="menu" aria-labelledby="more-btn" aria-hidden="true">
            <li class="more-menu-item" role="presentation">
                <form action="{% url 'quiz-result' quiz.id %}">
                    <button type="submit" class="more-menu-btn" role="menuitem" id='resultBtn'>Results</button>
                </form>
            </li>
            <li class="more-menu-item" role="presentation">
                <button type="button" class="more-menu-btn" role="menuitem" data-toggle="confirm"
                    data-id="{{quiz.id}}">Delete</button>
            </li>
            <li class="more-menu-item" role="presentation">
                <button type="button" class="more-menu-btn duplicate" role="menuitem" data-toggle="modal"
                    data-target="#duplicateModal" data-id='{{quiz.id}}'>Duplicate</button>
            </li>
        </ul>
    </div>
</div>

wepquiz/templates/quiz/duplicate_modal.html
{% load static %}

<div class="modal fade" id="duplicateModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Quiz</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id='duplicate_form' method="POST">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Name of duplicated quiz:</label>
                        <input type="text" class="form-control" name='quiz' value='{{quiz.name}}' required autofocus>
                        <button id='submit' type='submit' hidden></button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id='duplicateDone' type="button" class="btn btn-primary">Done</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'quiz/duplicate_quiz.js' %}"></script>

wepquiz/templates/quiz/navbar.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class=" navbar-brand" href="#">MCQ Maker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'quiz-list'%}">Quizzes<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
        </ul>
    </div>
</nav>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

wepquiz/templates/quiz/new_quiz.html
{% extends 'quiz/new_update_quiz_common.html' %}
{% load static %}

{% block content %}
<div class="container">

    <form action='{% url "new-quiz" %}' method='post' class="quiz-form">
        {% csrf_token %}

        {% include 'quiz/settings_modal.html' %}

        <div class="heading">
            <input type='text' class="heading__text" name='quiz' required autofocus placeholder="Quiz Name">
        </div>

        <div class="question">
            <label for="q_1">1.</label>
            <input type="text" name="q_1" id="q_1" class="quiz-form__question" required>

            {% include 'quiz/new_quiz_choices.html' %}

            <div class="footer">
                <div class="point">
                    <input type="number" name="1_point" value=1 min=0 required>
                    <span>points</span>
                </div>
                <div class='footerBtns'>
                    <button type="button" class='mcqDuplicateBtn duplicateBtn'>Duplicate</button>
                    <button type="button" class='deleteBtn'>Delete</button>
                </div>
            </div>
        </div>
        <button type='submit' id='submit' hidden></button>
    </form>
</div>

{% endblock content %}

wepquiz/templates/quiz/new_quiz_choices.html
{%for i in defaultNumberOfChoices %}

    <div class="quiz-form__ans">
        <input type="radio" name='1_radio_option' value='{{i}}' required>
        <span class="design"></span>
        <input type="text" name="1_option{{i}}" placeholder="Option {{i}}" required>
        <svg fill="#5c626f" class="delete_mcq_choice delete_choice" xmlns="http://www.w3.org/2000/svg"
            width="24" height="24" viewBox="0 0 24 24">
            <path
                d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z">
            </path>
            <path d="M0 0h24v24H0z" fill="none"></path>
        </svg>
    </div>

{% endfor %}

<div class="quiz-form__ans">
    <input type="radio">
    <span class="design"></span>
    <input type="text" class='add_mcq_choice' placeholder="Add Option">
</div>

wepquiz/templates/quiz/new_update_quiz_common.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap">

    <link rel="stylesheet" href="{% static 'quiz/new_quiz.css' %}">
    <link rel="stylesheet" href="{% static 'quiz/settings_modal.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</head>

<body>

    <header>
        <button type="button" class="btns" data-toggle="modal" data-target="#settingsModal">
            Settings
        </button>
    </header>

    <footer>

        <div class="btn-group dropup">
            <button type="button" id='add' class="btn btn-primary add_new">
                Add New
            </button>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
                <button id='addCheckbox' class="dropdown-item">Checkbox</button>
                <button id='addShort' class="dropdown-item">Short Answer</button>
                <button id='addMcq' class="dropdown-item">MCQ</button>
            </div>
        </div>

        <button id='save' class="btns"> Save </button>
    </footer>

    {% block content %}
    {% endblock content %}

    <script src="{% static 'quiz/createElements.js' %}"></script>
    <script src="{% static 'quiz/add_choice.js' %}"></script>
    <script src="{% static 'quiz/delete_choice.js' %}"></script>
    <script src="{% static 'quiz/delete_question.js' %}"></script>
    <script src="{% static 'quiz/duplicate_question.js' %}"></script>
    <script src="{% static 'quiz/settings_modal.js' %}"></script>
    <script src="{% static 'quiz/new_update_common.js' %}"></script>

</body>

</html>

wepquiz/templates/quiz/quiz_confirm_delete.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<div class="container mt-5">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the quiz "{{ object.name }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'quiz-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>

wepquiz/templates/quiz/quiz_detail.html
{% load static %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap">

<link rel="stylesheet" href="{% static 'quiz/quiz_detail.css' %}">

<footer>
    <form action="{% url 'quiz-update' object.id %}" method="GET">
        <button type='submit' id='edit' class="btns"> Edit </button>
    </form>
</footer>

<div class="container">
    <div class="heading">
        <h1 class="heading__text">{{object.name}}</h1>
    </div>

    <form class="quiz-form">

        {% for question in object.question_set.all %}

        {% include 'quiz/quiz_detail_common.html' %}

        {% endfor %}

    </form>

</div>

wepquiz/templates/quiz/quiz_detail_common.html
<div class="question">
    <div class="questionHeader">
        <p class="quiz-form__question">{{question.question}}</p>
        <div class="point">
            <p>{{question.point}}</p>
            {% if question.point == 1 %}
            <span>point</span>
            {% else %}
            <span>points</span>
            {% endif %}
        </div>
    </div>

    {% for choice in question.choice_set.all %}

    <label class="quiz-form__ans" for="{{forloop.parentloop.counter}}_choice{{forloop.counter}}">

        {% if question.type == 'mcq' %}

        <input type="radio" id="{{forloop.parentloop.counter}}_choice{{forloop.counter}}" required
            name='{{forloop.parentloop.counter}}_radio_option' value='{{forloop.counter}}'>

        <span class="design"></span>

        {% elif question.type == 'checkbox' %}

        <input type="checkbox" id="{{forloop.parentloop.counter}}_choice{{forloop.counter}}"
            name='{{forloop.parentloop.counter}}_checkbox_{{forloop.counter}}'>

        {% endif %}

        <span class="text">{{choice.choice}}</span>

    </label>

    {% endfor %}


    {% if question.type == 'short' %}

    <label class="quiz-form__ans">

        <input type="text" name='{{forloop.counter}}_short_1' required>

    </label>

    {%endif%}

</div>

wepquiz/templates/quiz/quiz_list.html
{% load static %}

<link rel="stylesheet" href="{% static 'quiz/quiz_list.css' %}">

{% include 'quiz/navbar.html' %}

<div class="create_new_quiz">
    <a href="{% url 'new-quiz' %}" class="btn btn-outline-info" role="button">Create a Quiz</a>
</div>

<header>
    <h2>Quizzes</h2>
    <hr>
</header>


<div class="container mt-5">
    <div class="row">

        {% for quiz in object_list %}

        {% include 'quiz/duplicate_modal.html' %}

        <form id='{{quiz.id}}' method="POST" action="{% url 'quiz-delete' quiz.id %}" hidden>
            {% csrf_token %}<input type="submit" value="DELETE">
        </form>

        <div class="col-3 mb-4">
            <div class="card bg-dark text-white h-100">
                <div class="card-body">

                    <h4 class="card-title mb-4">
                        {{quiz.name}}
                    </h4>
                    <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
                    <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                </div>
                <div class="card-footer">
                    <a href="{% url 'quiz-update' quiz.id%}" class='card-link'>Edit</a>
                    <a href="{{quiz.get_absolute_url}}" class="card-link">Preview</a>
                    <a href="#" class='card-link share' data-value='{{quiz.id}}' data-toggle="tooltip"
                        title="Link Copied to Clipboard!" 
                        {% if quiz.timeLimit is not None and quiz.startDateTime is not None %} data-timer-set='1' {% else %} data-timer-set='0' {% endif %}>Share</a>
                    {% include 'quiz/3dot_menu.html' %}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>

</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'quiz/delete-popup.css' %}">
<script src="{% static 'quiz/delete-popup.js' %}"></script>
<script src="{% static 'quiz/quiz_list.js' %}"></script>

wepquiz/templates/quiz/quiz_update.html
{% extends 'quiz/new_update_quiz_common.html' %}
{% load static %}

{% block content %}
<div class="container">

    <form action='{% url "quiz-update" quiz.id %}' method='post' class="quiz-form">
        {% csrf_token %}

        {% include 'quiz/settings_modal.html' %}

        <div class="heading">
            <input type='text' class="heading__text" name='quiz' required autofocus value={{quiz.name}}>
        </div>

        {% for question in quiz.question_set.all %}

        <div class="question">
            <label for="q_{{forloop.counter}}">{{forloop.counter}}.</label>
            <input type="text" name="q_{{forloop.counter}}" id="q_{{forloop.counter}}" class="quiz-form__question"
                required value='{{question.question}}'>

            {% include 'quiz/quiz_update_choices.html' %}

            <div class="footer">
                <div class="point">
                    <input type="number" name="{{forloop.counter}}_point" value='{{question.point}}' min=0 required>
                    <span>points</span>
                </div>
                <div class='footerBtns'>
                    <button type="button" class="duplicateBtn
                    {% if question.type == 'mcq' %}
                    mcqDuplicateBtn
                    {% elif question.type == 'checkbox' %}
                    checkboxDuplicateBtn
                    {% elif question.type == 'short' %}
                    shortDuplicateBtn
                    {% endif %}
                    ">Duplicate</button>
                    <button type="button" class='deleteBtn'>Delete</button>
                </div>
            </div>
        </div>

        {% endfor %}
        <button type='submit' id='submit' hidden></button>
    </form>
</div>

{% endblock content %}

wepquiz/templates/quiz/quiz_update_choices.html
{% for choice in question.choice_set.all %}

    <div class="quiz-form__ans">
        {% if question.type == 'mcq' %}

        <input type="radio" required name='{{forloop.parentloop.counter}}_radio_option'
            value='{{forloop.counter}}' 
            {% if question.mcqanswer.answer == forloop.counter %} checked {% endif %}>
        <span class="design"></span>

        {% elif question.type == 'checkbox' %}

        <input type="checkbox" name='{{forloop.parentloop.counter}}_checkbox_{{forloop.counter}}' 
        {% for answer in question.checkboxanswer_set.all %}
        {% if answer.answer == forloop.parentloop.counter%} checked {% endif %}
        {% endfor %}>

        {% endif %}

        <input type="text" required name="{{forloop.parentloop.counter}}_option{{forloop.counter}}"
            value='{{choice.choice}}'>
            
        <svg fill="#5c626f" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
        viewBox="0 0 24 24"
        class="delete_choice
        {% if question.type == 'mcq' %}
        delete_mcq_choice
        {% elif question.type == 'checkbox' %}
        delete_checkbox_choice
        {% endif %}
        ">
            <path
                d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z">
            </path>
            <path d="M0 0h24v24H0z" fill="none"></path>
        </svg>
    </div>

{% endfor %}

{% if question.type == 'short' %}

    {% for shortAnswer in question.shortanswer_set.all %}
        
        <div class="quiz-form__ans">

            <input type="text" name='{{forloop.parentloop.counter}}_short_{{forloop.counter}}' 
            value="{{shortAnswer.answer}}" required>

            <svg fill="#5c626f" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            viewBox="0 0 24 24"
            class="delete_choice delete_short_choice">
                <path
                    d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z">
                </path>
                <path d="M0 0h24v24H0z" fill="none"></path>
            </svg>

        </div>

    {% endfor %}
    
{%endif%}
        
{% if question.type == 'mcq' %}

    <div class="quiz-form__ans">
        <input type="radio">
        <span class="design"></span>
        <input type="text" class='add_mcq_choice' placeholder="Add Option">
    </div>

{% elif question.type == 'checkbox' %}

    <div class="quiz-form__ans">
        <input type="checkbox">
        <input type="text" class='add_checkbox_choice' placeholder="Add Option">
    </div>

{% elif question.type == 'short' %}

    <div class="quiz-form__ans">
        <input type="text" class='add_short_choice' placeholder="Add Answer">
    </div>

{% endif %}

wepquiz/templates/quiz/result.html
{% load static %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'quiz/result.css' %}">

<h1 class="heading__text">Results of {{quiz.name}}</h1>

<div class="container">
    <table class="table table-dark table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Score</th>
                <th scope="col">Report</th>
            </tr>
        </thead>
        <tbody>
            {% for taker in takers %}

            <tr>
                <td>{{taker.name}}</td>
                <td>{{taker.email}}</td>
                <td>{{taker.score}}</td>
                <td><a href="{% url 'result' quiz.id taker.id %}">Link</a></td>
            </tr>

            {%endfor%}
        </tbody>
    </table>
</div>

wepquiz/templates/quiz/settings_modal.html
<div class="modal fade" id="settingsModal" role="dialog" data-backdrop="static" data-keyboard="false"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Settings</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button> -->
            </div>
            <div class="modal-body">
                <div class="timer-checkbox">
                    <p> Enable Timer </p>
                    <label class="col-form-label switch">
                        <input type="checkbox" name='timer-enabled' autofocus {% if quiz.timeLimit is not None %}
                            checked {%endif %}>
                        <span class="slider round"></span>
                    </label>
                </div>

                <div class="timer mt-2" {% if quiz.timeLimit is None %} style="display: none;" {%endif %}>
                    <label class="col-form-label mt-2">Timer Duration (in mins)</label>
                    <input type="number" name='time-limit' min=1 value='{{quiz.timeLimit}}'>

                    <label class="col-form-label mt-2">Start Date</label>
                    <input type="date" name='start-date' value='{{startDate}}'>

                    <label class="col-form-label mt-2">Start Time</label>
                    <input type="time" name='start-time' value='{{startTime}}'>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id='saveSettings' data-dismiss="modal">Save</button>
                <button type="button" class="btn btn-danger" id='cancelSettings' data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>